apiVersion: v1
kind: Secret
metadata:
  name: airgap-runtime
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: airgap-runtime
type: Opaque
stringData:
  {{- range $key, $value := .Values.runtimeEnvironment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
